services:
  postgres:
    image: postgres:16
    container_name: animales-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_HOST}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  app:
    build: .
    container_name: animales-app
    ports:
      - '3000:3000'
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
volumes:
  animales-pg-data: