services:
  postgres:
    image: postgres:16
    container_name: animales-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB:       animalesDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
  app:
    build: .
    container_name: animales-app
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: animalesDB
      PORT: 3000
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
volumes:
  animales-pg-data: